Fix mime type of documentation
Fixes
> Checking dist\energy_datetime-0.1-py3-none-any.whl: FAILED
ERROR    `long_description` has syntax errors in markup and would not be rendered on PyPI.
         No content rendered from RST source.
Checking dist\energy_datetime-0.1.tar.gz: PASSED with warnings
WARNING  `long_description` missing.
ERROR: InvocationError for command \.tox\test_packaging\Scripts\twine.EXE' check 'dist/*' (exited with code 1)