don't re-use `calendar` for a variable of different type
Mypy was complaining about the return type hint because the type of `calendar` changed between instantiation and return.
This introduces a second variable which has the expected type. Its typehint is initially wrong but correct after the first loop iteration and at return

Fixes
> energy_datetime\calendar.py:63: error: Incompatible return value type (got "BdewDefinedHolidays", expected "HolidaySum")  [return-value]